services:
  postgres:
    image: postgres:17
    container_name: postgres_spring
    restart: always
    environment:
      POSTGRES_DB: pruebaTecnica
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5440:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: crud
    container_name: spring_app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/pruebaTecnica
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET_KEY: "E4xEHxWa6AUHmbfvQxQiBM1oECP07drQ7/WdIyCWgxE="
    depends_on:
      - postgres

volumes:
  postgres_data:
